### PR TITLE
Make vendor card hoverable and animate button link on hover

### PR DESCRIPTION
**Pull request by mbeiswenger**

### CODE REVIEW

**Comment by noudadrichem** [comment]
Thank you for your contribution! I'll take a look at this asap!

**Comment by noudadrichem** [comment]
Hee @mbeiswenger ,

Tyvm for the contribution. Tbh, I'm not sure changing state is necessary to fix this relatively simple 'hover' animation. It could easily be done with CSS which also makes the performance a whole lot better. 
I like the way you're going and could also be usefull for the regular `ImageCard` component. 
But take another look at this, it could be done without updating states etc..

**Comment by mbeiswenger** [comment]
I actually did implement it for the `ImageCard` component as well. The only reason I didn't implement this in CSS is because the styles would be contained in `image-card.scss` and/or `vendor-card.scss`  on the `:hover` pseudo-selector even though it's styling the `ButtonLink` component which has its own styles. Although I could just put them in a new style file cause the styles aren't scoped? Not sure exactly what you're looking for here.

**Comment by noudadrichem** [comment]
Valid point, imo the effect is on the card so the styling could go in the `image-card.sscs` all related styling for that component is there even for the button hover. 
(So kind of just copy the style from the buttonlink for now)

**Comment by noudadrichem** [comment]
Closing this because it's fixed in #30 . Also lot of conflicts here. haha.

**Pull request closed without merging**
