### PR TITLE
Fix: Favoriting no longer changes scroll position

### PR DESCRIPTION
**Pull request by onebree**
By wrapping the entire contents of ImageCard inside a `<Link />` instance, click events from that conflicted with those on the favorite button.

### CODE REVIEW

**Comment by onebree** [comment]
Still a draft, as I need to get sign-ins to work properly in order to make sure this change works.

**Comment by noudadrichem** [comment]
Nice! Thanks for figuring this out! 
Sign-in with Reddit is not possible on local but Google should work fine.!

**Comment by noudadrichem** [comment]
I see you made it so that only the img and the title are links. Should be feature proof if we maybe add more clickable stuff in the card later on. Thanks!

**Comment by onebree** [comment]
Yep! Those are really the only things needed for links, and makes more sense. I am trying to figure out though how we can wrap the image in an `<a />` tag for proper HTML and tab-navigation. It may not be a huge deal though, as tab-navigation works by highlighting the title at least.

**Comment by noudadrichem** [comment]
I checked out on this and discovered that I still go up when I like a set..

**Comment by noudadrichem** [comment]
And now I'm really not sure why.

**Comment by noudadrichem** [comment]
It has to do with the dispatch in the `userWantSet` function in the `ImageCard` component. The dispatch causes a re-render and makes it jump to the top.. weird.. as other state changes doesn't have this effect.

**Comment by noudadrichem** [comment]
So, I kind of fixed this by memorizing window.scrollTop and setting it again. Which is really not the way to go. So if you still want to investigate this I would be happy! It's something about the renderer.

**Comment by onebree** [comment]
Sounds good. I haven't been able to really look at the code lately. So it's
good you got a bandaid for it.

I'll try to at least get this issue complete this month.

**Pull request closed without merging**
